name: Scrape latest  question

on:
  schedule:
    - cron:  '6 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: setup python
      uses: actions/setup-python@v2
      with:
       python-version: 3.8
    - name: install python packages
      run : |
        python -m pip install --upgrade pip
        pip install requests==2.24.0
        pip install beautifulsoup4==4.9.1
        pip install PyYAML==5.3.1
    - name: Execute py script
      working-directory: ./HFCCore/management/commands
      run: python question_scraper.py   
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
